export const feedbackCopy = {
  audioUnavailable: "Audio is unavailable right now.",
  sceneImageUnavailable: "Image unavailable.",
  comingSoon: "Coming soon",
  speakingMistakePracticeUnavailable: "Speaking review will be available soon.",
  listenFirst: "Listen to the word first.",
  tapObject: "Tap an object in the picture.",
  correctObject: "Correct object.",
  correctSpelling: "Correct spelling.",
  tryAgain: "Try again.",
  tryOnceMore: "Try once more.",
  recording: "Recording...",
  recordingCancelled: "Recording cancelled.",
  recordingSaved: "Recording saved.",
  recordingTooShort: "That recording was too short. Please try again.",
  recordingFailed: "Recording did not save. Please try again.",
  microphoneNeededTitle: "Microphone needed",
  microphonePermission: "Microphone access is needed for speaking practice.",
  checkingPronunciation: "Checking your pronunciation...",
  greatPronunciation: "Great pronunciation.",
  recognitionNotClear: "I did not catch the word. Please try again.",
  recognitionFailed: "Pronunciation check is unavailable. Please try again.",
  speechStatusReady: "Speech practice ready.",
  favoriteAudioUnavailable: "Audio is unavailable right now.",
  noMistakesForType: (typeLabel: string) => `No ${typeLabel} mistakes yet`
} as const;
